// @flow
export type AppEvent = "INITIALIZE" 
| "SOME_EVENT"
| "SAVE_TOKEN"
| "SET_FOCUSED_SCREEN"
| "SAVE_USER_INFO"
| "DEVICE_STATUS_CHANGE"
| "SAVE_USER_DEVICES"
// | "CHOOSE_LIST_DEVICES_TO_ADD_ROOM"